### ISSUE TITLE
ULG files in /var/lib/mavlink-router grow without bound, filling partition

### ISSUE THREAD

**Issue by JoshLikesBeer** [intel/mavlink-router#131]
I have an Intel Aero sitting on a desk plugged into the wall while I'm doing development work. The Mavlink router daemon is continuously writing to a *.ulg file at a rate of about 3MB per minute, filling the partition on a regular basis.

I know of two workarounds. One is to set up a cron job that deletes the *ulg files and restarts the Mavlink router daemon, and the other is to edit the /etc/mavlink-router/main.conf and comment out the Log setting.

Is there a setting to roll the *.ulg files when they get to a certain size and to overwrite older ones, similar to the log4j rollover strategy, or is there another way to limit the size of the files produced without restarting Mavlink or turning off this logging altogether?

Here is my /etc/mavlink-router/main.conf:
```
[General]
TcpServerPort=5760
ReportStats=false
Log=/var/lib/mavlink-router/

[UartEndpoint uart]
Device = /dev/ttyS1
Baud = 921600,460800

[UdpEndpoint wifi]
Mode = Normal
Address = 192.168.8.255

[UdpEndpoint ethernet-over-usb]
Mode = Normal
Address = 192.168.7.255

[UdpEndpoint csd]
Mode = Normal
Address = 0.0.0.0
Port = 80550
Mode = eavesdropping
```

Thanks,
Josh Davis

**Comment by lucasdemarchi** [comment]
There isn't, but a patch implementing it would be welcome.

**Comment by JoshLikesBeer** [comment]
Thanks for the reply. I don't know C++ well enough to implement it myself, so I'll just turn off the logging.
