### ISSUE TITLE
TCP server not working

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [intel/mavlink-router#137]
I am trying to use the TCP server of the mavlink-router.

However, I cannot get any connection of the port I have specified in the configuration file.
I am getting a good stream over the UDP endpoint

Could anyone clarify if the TCP server for the mavlink-rotuer is working?

**Comment by lucasdemarchi** [comment]
What do you have in your configuration file?

**Comment by Jaeyoung-Lim** [comment]
@lucasdemarchi Sorry about the fuss. It was a issue with my system setup.

The TCP server works fine.
