### ISSUE TITLE
Autogen Failed on Raspi 3 B+

### ISSUE THREAD

**Issue by tizianofiorenzani** [intel/mavlink-router#144]
I have already installed mavlink-router successfully on multiple raspberry Pi 3.

I am facing the following error when running ./autogen:

./configure: line 5897: syntax error near unexpected token `disable-static'
./configure: line 5897: `LT_INIT(disable-static pic-only)'

I installed autoconf package

**Comment by tizianofiorenzani** [comment]
After running 

autoconf
aclocal

the ./autogen went through

**Comment by lucasdemarchi** [comment]
If you have the git repository cloned, this should always be sufficient to build from scratch:

```
git clean -ffxd
./autogen.sh c
make
```

If you are not moving the source code around from one board to another (or trying to use the .zip downloaded from github), then just the last command is sufficient.

**Comment by tizianofiorenzani** [comment]
That actually worked great

**Comment by tizianofiorenzani** [comment]
I got the same problem today with a fresh install. Tried everything, same issue

**Comment by tizianofiorenzani** [comment]
Got clone

**Comment by FLYBYME** [comment]
Fresh install on a pi3 `sudo apt install libtool` seems to fix it.
