### ISSUE TITLE
compile failed on raspian

### ISSUE THREAD

**Issue by dk7xe** [intel/mavlink-router#158]
Just tried to install mavlink router on another raspberry running raspian but `make` failed with

`~/src/mavlink-router $ make`
`  GEN      include/mavlink/ardupilotmega/mavlink.h`
`Traceback (most recent call last):`
`  File "./modules/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>`
`    from pymavlink.generator import mavgen`
`  File "/home/pi/src/mavlink-router/modules/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>`
`    from future import standard_library`
`ImportError: No module named future`
`Makefile:1609: die Regel für Ziel „include/mavlink/ardupilotmega/mavlink.h“ scheiterte`
`make: *** [include/mavlink/ardupilotmega/mavlink.h] Fehler 1`
 
**process steps**

1.  did a git clone
2. executed `git submodule update --init --recursive`
3. executed `./autogen.sh && ./configure CFLAGS='-g -O2' \
        --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib \
    --prefix=/usr`
4. executed `make`

**Comment by lucasdemarchi** [comment]
Error message above: ImportError: No module named future

**Comment by dk7xe** [comment]
Thanks for pointing me into the right direction.
`apt install python-future` solved the problem.

**Comment by sparklytopaz** [comment]
> Thanks for pointing me into the right direction.
> `apt install python-future` solved the problem.

I installed this but yet facing the same error

**Comment by m1baldwin** [comment]
I have also seen this error, and not been able to fund a solution. I have also tried installing with 'pip install future' but this did not seem to help.

**Comment by Jaeyoung-Lim** [comment]
@m1baldwin @sparklytopaz try `apt install python3 future`

**Comment by m1baldwin** [comment]
Thanks @Jaeyoung-Lim , that seemed to solve the issue for me!
