### ISSUE TITLE
git submodule status --recursive : fatal error 

### ISSUE THREAD

**Issue by benittotomy** [intel/mavlink-router#188]
While trying to install Mavlink-router to raspberry pi connected with Pixhawk, i am getting an error as follows....

pi@raspberrypi:~ $ git submodule status --recursive
fatal: not a git repository (or any of the parent directories): .git

Does anyone encountering the same issue?
I am following the readme file.

**Comment by Jaeyoung-Lim** [comment]
@benittotomy You in the wrong directory. Do it inside the mavlink-router repo

**Comment by benittotomy** [comment]
@Jaeyoung-Lim Thank You. It is working. 
Could you please help me to Build that packages. Which command i have to follow ?
