### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by benittotomy** [intel/mavlink-router#191]
pi@raspberrypi:~/mavlink-router $ mavlink-routerd -e 192.168.7.1:14550 -e 127.0.0.1:14550 /dev/ttyS1:1500000
Could not open conf file '/etc/mavlink-router/main.conf' (No such file or directory)

**Comment by steveatinfincia** [comment]
Should be a non-fatal error, it still works right?

**Comment by lucasdemarchi** [comment]
does the file exist? You can suppress the error by passing an empty (or /dev/null) config file in the command line
