### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rmackay9** [intel/mavlink-router#200]
@lucasdemarchi, no great pressure but it looks like the last official release of mavlink-router was in 2017.. we're thinking about releasing an updated APSync image in the near-ish future, we can do that off of master mavlink-router but an official release would be nice.

**Comment by lucasdemarchi** [comment]
Sure. I can do it this week. Thanks

**Comment by lucasdemarchi** [comment]
@bkueng do you have anything critical pending? I just pushed some cleanups of gcc and clang warnings and went through the issues to check if there was anything urgent.

**Comment by bkueng** [comment]
No, nothing important is pending from me.

**Comment by lucasdemarchi** [comment]
v2 is released
