### ISSUE TITLE
pl update mavlink submodule

### ISSUE THREAD

**Issue by olliw42** [intel/mavlink-router#201]
it is fantastic that version 2 just came out few days ago, sadly the mavlink submodule is 2 years old however ...
it would be great if it could be updated to the latest and freshest :)
thx

**Comment by lucasdemarchi** [comment]
Yep, I didn't do it before release because it will probably bring bugs with it, and I didn't want to delay the release.

**Comment by olliw42** [comment]
many thx, this was swift :+1:
