### ISSUE TITLE
Routing not conform with MAVlink routing rules: Bug, feature, or what?

### ISSUE THREAD

**Issue by olliw42** [intel/mavlink-router#207]
mavlink-router is not routing the messages according to the MAVLink routing rules: 

While a target system id is correctly respected, a target component id is not always correctly respected.

I believe to see that very clearly in my testings, and I think that this is also very obvious from the code:
https://github.com/intel/mavlink-router/blob/18891603c436dd360bb77589f4120507124856ad/src/mavlink-router/endpoint.cpp#L336-L349

So, the question is, why is that? Is there a (good?) reason for that behavior, or is it just because of "history", or is this indeed a bug?

I would argue it is clearly a bug, since it is not conform with the rules and produces (much) unwanted traffic, and that's why I'm actually not really pleased by this behavior, also because I fail to see a really good reason for it.

any clarification on this point would be much appreciated.

many thx, Olli

**Comment by lucasdemarchi** [comment]
> mavlink-router is not routing the messages according to the MAVLink routing rules:

what rules?

> I believe to see that very clearly in my testings,

can you expand on this? It would be interesting to know what you are testing and how you are seeing a wrong behavior.

what mavlink-router does is to route packets from one endpoint to another. In order to do that it uses it knowledge of "is this system available on this endpoint?". If yes, then it writes the packet to that endpoint (with the exception of "is it the same endpoint?" to avoid loops - see commit ad367033fd75f1535c82d2e604c7e6be93e16ad5)

From the code you mentioned, what appears wrong is the comment: we actually route any packet to the endpoint as long as the systemid matches (or is a broadcast).

We can't add a match on the compid, because that would imply that every component would need to broadcast at least one packet (usually

**Comment by olliw42** [comment]
> what rules?

https://mavlink.io/en/guide/routing.html

> can you expand on this? It would be interesting to know what you are testing and how you are seeing a wrong behavior.

Here a case demonstrating the violation of the MAVLink routing rules:


Setup:
-----

ArduPilot - RPi3 - STorM32(Gimbal&Camera)

on the RPi3 in addition to mavlink-router runs a py script, which connects to tcp:5760 and emits a heartbeat with 1/191

so we have 4 MAVLink components, and 3 endpoints: 
* ArduPilot: 1/1 on endpoint [4]
* Gimbal: 1/154 on endpoint [5]
* Camera: 1/105 on endpoint [5]
* py script: 1/191 on endpoint [8]


Case:
------

Let's consider a message send by the autopilot (source 1/1) with target 1/154 (e.g. a CMD LONG). 
Here a relevant snippet from the debug output of mavlink-router:

```
:
:
UART: Got 2 bytes [4]
Endpoint [4] got message to 1/154 from 1/1
	Known endpoints:
		1/1
Endpoint [5] got message to 1/154 from 1/1
	Known endpoints:
		1/154
		1/105
Endpoint [5] accepted message to 1/154 from 1/1
UART: [5] wrote 55 bytes
Endpoint [8] got message to 1/154 from 1/1
	Known endpoints:
		1/191
Endpoint [8] accepted message to 1/154 from 1/1
TCP: [8] wrote 55 bytes
:
:
```

So, obviously, endpoint [4] got a message from the autopilot (1/1) with target 1/154. 


accept_msg():
-------------

Let's now consider the accept_msg() function for endpoint [8]. 
It has only 1/191 in it's list of known ids.

Let's go through the if conditions starting at line 337:

if() at L.337: not fullfilled, since target system is not broadcast, so go on

if() at L.341: not fullfilled, since target sys-comp pair is not in list, so go on

if() at L.345: is fullfilled, since target sys is in list, hence terminate with accepted = true


Result:
-------

Therefore, the message from 1/1 with target 1/154 is also send to 
endpoint [9], i.e., the component 1/191, which explictely violates the routing
rules, according to which it should NOT have been sent to component 1/191 on endpoint [8], 
but only to component 1/154 on endpoint [5].

Q.E.D

This is btw also exactly what I see in the reality: The py script on the RPi3 indeed receives  the said message(s). When I change the sys id of the py script from 1 to something else, i.e., something different from the autopilot's sys id, when the said message is indeed not forwarded to endpoint [8], which is totally explained by the code, since then the if() at L.345 would not be true and accept_msg() for endpoint [8] would terminate with false. So, Q.E.D by code and by experiment :)

**Comment by lucasdemarchi** [comment]
> > what rules?
> 
> https://mavlink.io/en/guide/routing.html

warning that the documentation was written post-implementation. And AFAIK was written with the intent to match mavlink-router's behavior.

> ## Result:
> Therefore, the message from 1/1 with target 1/154 is also send to
> endpoint [9], i.e., the component 1/191, which explictely violates the routing
> rules, according to which it should NOT have been sent to component 1/191 on endpoint [8],
> but only to component 1/154 on endpoint [5].

Let's put the rules here explicitly for the routing case:

Systems should forward messages to another link if any of these conditions hold:

- It is a broadcast message (target_system field omitted or zero).
- The target_system does not match the system id and the system knows the link of the target system (i.e. it has previously seen a message from target_system on the link).
- The target_system matches its system id and has a target_component field, and the system has seen a message from the target_system/target_component combination on the link.

It seems to me mavlink-router does conform with the rules. mavlink-router itself doesn't have a system-id. So only the first 2  conditions apply and they don't talk about component id and rather only about considering the system id.

Once upon a time I think we cared about the pair sysid/compid. And the problem was that we couldn't route messages unless all components sent at least one message. And not all components do this.

I think it would be sensible to change it back to sysid + compid, but then we also need to change the rules you quote.

@bkueng @hamishwillee thoughts?

> This is btw also exactly what I see in the reality: The py script on the RPi3 indeed receives the 
> said message(s). When I change the sys id of the py script from 1 to something else, i.e., 
> something different from the autopilot's sys id, when the said message is indeed not forwarded to > endpoint [8],

And that is what people should do... Imagine that your py script is a GCS, it would have a different sysid.

**Comment by olliw42** [comment]
I'm sorry to say, but I disagree, the arguments are IMHO incorrect

btw, I'm not concerned about whatever history there was, I would suggest to just consider the current state.

as regards the rules, the problem with them is indeed that some few sentences when isolated are indeed incomplete in a mathematical sense, but from the context it's pretty clear what the rules are. 

If you want I could disect the text in pieces, but I'm not sure it's worthwhile. So let me just e.g. cite "Non-broadcast messages must only be sent (or forwarded) to known destinations". I also like to refer to common sense that it makes really no sense that a message with both a target sys id and target comp id should be forwarded to an endpoint which hasn't seen that component.

In short, it's IMHO pointless to argue if such message should be forwarded or not, the answer can only be no.

> Once upon a time I think we cared about the pair sysid/compid. And the problem was that we couldn't route messages unless all components sent at least one message. And not all components do this.

I don't agree. There are things which don't send but only listens, from top of my head only a OSD would come to my mind. However, these can be attached to ANY MAVLink channel one likes and no one would add a router or waste a full endpoint just for them. If there really should be cases there this nevertheless is needed, I would argue that these are sooo special that one really shouldn't break the large majority just for the benefit of the small minority. I rather would argue that one should add an option if this really ever had been of practical relevance.

> I think it would be sensible to change it back to sysid + compid,

I would strongly urge to do so :)

btw, the comment in L.344 is actually saying the correct thing: 
`// This endpoint has the target of message (sysid, but compid is broadcast): accept `
it's just that the if() which follows isn't doing what the comment is saying :)

> And that is what people should do... Imagine that your py script is a GCS, it would have a different sysid.

???

but my py script is not a GCS but a component of the system ... and it's really irrelevant that it was a py script, it could have been a third physical endpoint with e.g. the camera attached to it and the very same problem would have occurred .... are you saying that cameras and gimbals and so on should be GCSes too, each with its own sys id? I don't think so, so, the example I've given should be quite compelling.

**Comment by hamishwillee** [comment]
FWIW the [docs](https://mavlink.io/en/guide/routing.html#routing-detail) are contradictory. 
- The bullet points say that a system routes 
  - all messages to *other system IDs* (that it has seen before) irrespective of whether it has seen the particular component ID before
  -  to components with the *same system id* only if has seen the component id. 
- The _note_ says that a system must have seen both the component and system id to route. 

The difference being whether or not you'd route to another system if you hadn't also seen it's particular component id.
The heartbeat is a broadcast, so the assumption behind the bullets would appear to be that a system might not re-transmit the heartbeats of its components. 

I don't know which is "correct" or which is a better implementation, or what might break by changing this one way or the other. The bullet point option would seem more forgiving. @bkueng do you have insight?

**Comment by olliw42** [comment]
the "problem" which seems to confuse you guys is that the routing rules are obviously written for an autopilot, which has a system/component id itself. But a router doesn't. However, that's really a no-brainer since it's obvious how to read the sentences with this in mind.

Since there is a "funny" way of citing going on here, I copy the actual rules 1-to-1 to here:

> Systems should forward messages to another link if any of these conditions hold:
> * It is a broadcast message (target_system field omitted or zero).
> * The target_system does not match the system id and the system knows the link of the target system (i.e. it has previously seen a message from target_system on the link).
> * The target_system matches its system id and has a target_component field, and the system has seen a message from the target_system/target_component combination on the link.
> 
> Non-broadcast messages must only be sent (or forwarded) to known destinations (i.e. a system must previously have received a message from the target system/component).

Which for a router obviously translates into:

Routers should forward messages to another link if any of these conditions hold:
* It is a broadcast message (target_system field omitted or zero).
* The router knows the link of the target system (i.e. it has previously seen a message from target_system on the link).
* It has a target_component field, and the router has seen a message from the target_system/target_component combination on the link.

Non-broadcast messages must only be sent (or forwarded) to known destinations (i.e. a system must previously have received a message from the target system/component).

Your contradiction for instance only comes about because you have not correctly cited the note sentence but modified it. You are saying "The note says that a system must have seen **both** the component and system id to route." which is really not what the sentence says. The sentence is admittedly not well phrased since one might confuse it with the case target_system=not-broadcast & target_component=broadcast, but this doesn't make it a contradiction. (dito for your bullets).

You also just could look at the comments in the c file which EXACTLY describe the three bullets. The only thing which has happened is that the 3rd if statement had a bug (and there is also a bug with avoiding reflections, but that's for another day)

It's  amazing that you guys are making it appear rocket science. It's a trivial bug. End of story. So let's correct it and continue.

:)

**Comment by hamishwillee** [comment]
@olliw42 Writing clear and unambiguous text is much harder than rocket science, at least according to the rocket scientists I have worked with (technically only one, but let's not let the small sample size get in the way of a good story).

The problem with the note is that it **does** imply that you must have received a message from **both** the target and component. Bullet 2 fails this case, because the message only needs to resolve to a known system, not a known system and component. 

IF the bullet points are correct then we probably should just delete the note.

**Comment by olliw42** [comment]
:) 
YES
but, even if an isolated sentence doesn't have the mathematical preccission to stand alone we nevertheless can make sense of all statements in combination. It is a great difference to say that there is a contradiction and put into question what the rules are or which ones one should follow than to just state that the sentences are by themselves not sufficiently precise and not to put the rules into question.

In case of your contradiction, let me give an example:
* red cars may go wherever they want
* yellow cars may only drive along highway 66

These statements do NOT imply that there are only red and yellow cars!! Only if and only if it would have been states so it would be so.

But this is exactly what you do, you make an assumption of exclusiveness which by the other bullets is not supported, since the other bullets make it clear that there are (at least) 3 cases and not only 2! The contradiction appears only because YOU want to read that sentence in the way you want to read it, but the sentence can also be read to make perfectly sense and contribute to the common case.

Obviously, with allowing a false assumptions one can proof everything, even https://ergodicityeconomics.com/2018/03/27/economics-101-bertrand-russell-is-the-pope/. Since also some other sentences are somewhat imprecise we could go on and construct 1 million "contradictions" and spend the rest of our lives with that ... but my point is, it's not going to lead us to anywhere. 

We should not have to discuss what the rules are. The sentences as a whole are not incorrect, just maybe somewhat imprecise, and I understand you may want to improve the sentences. But this should not make us discus what the rules are.

In order to help it forward, here a rather systematic analysis:

![mavroute-table](https://user-images.githubusercontent.com/6089567/78539433-d8202e00-77f2-11ea-8779-be82cd4d724a.jpg)

So, phrasing sentences properly might be close to rocket science, I would not disagree with that, but the content they try to describe is certainly not ;)

**Comment by lucasdemarchi** [comment]
@olliw42 as I said before, the docs (or spec if you wish) were written post-fact. I'm only concerned by possible bugs that a change in the current behavior might cause. Hence why I'm trying to be cautious on merging it.

The docs can be updated later to make it as clear as one wants.

**Comment by hamishwillee** [comment]
Ollie, perhaps rather than spending so long explaining why I am wrong, perhaps you might want to propose text that such that I can't misinterpret it.

**Comment by olliw42** [comment]
@hamishwillee
I think we just agreed that the text part is much harder than rocket science ... so, above my paygrade
;)

**Comment by hamishwillee** [comment]
I'm hiding.

@lucasdemarchi Your main concern is components that don't broadcast their ID right? Essentially either components have to emit heartbeat OR component routing always has to be broadcast to channel where we saw the system. Otherwise routing can potentially fall over in some cases.

Can you point me at any cases of things that don't emit a heartbeat with their component?
I have seen cases like this in the past (as you say, listen-only-nodes), primarily in autopilot code that does component as a kind of subsystem but only emits the autopilot component id.

**Comment by lucasdemarchi** [comment]
@hamishwillee our poor test suite :)

**Comment by olliw42** [comment]
let's analyze what components would not broadcast their ID

1. components which never send a message
2. components which use an invalid source and/or component ID (value 0)

Case 1 I argued before should never be a practical problem since there is no reason to stick them to an extra port, but instead could always be wired to a Tx of any other component. If really needed, I argued one could handle that by adding a new option to the config file, which tells that the endpoint should send out messages even if there is no incoming messages. Conceptually and logically it actually would make sense to me to rather handle exceptional cases via config.

Case 2 must not occur by the spec.

Unfortunately, e.g. DroneKit appears to fall into category 2. So, such trouble makers exist. I'm not convinced however one should give them the credit to uphold routers doing proper routing.

Note that case 2 does not imply that the component sends out a heartbeat. And it seems that none of the routers available use heartbeats to detect the presence of components, but any message, and I think that's not a bad thing. 

From a general point, I'm actually puzzled it's you who are now making a connection to a heartbeat here, given that it was me who for a year argues that one should require by spec that any component must send out a heartbeat, which you MAVLink guys sometimes appear to agree with and most times disagree with. IMHO it would be really really helpful, and actually really really high time, to finally clarify MAVLink in this most basic point. Please consider this as a reminder to this point. :)

**Comment by lucasdemarchi** [comment]
I do think you have a point. I checked what the test is doing .... and it's silly, so I don't care much about it. We might as well rewrite that.

**Comment by lucasdemarchi** [comment]
Patch merged, thanks. Let's figure out what to do with the test failing...

**Comment by olliw42** [comment]
great, THANKS
so I close this here
