### ISSUE TITLE
Stopping sending bin logs after failsafe

### ISSUE THREAD

**Issue by Dan-Moss** [intel/mavlink-router#226]
Mavlink router is stopping sending bin logs over to a companion computer when a failsafe is happening.
using a cube orange on 4.0.3 ArduCopter

**Comment by lucasdemarchi** [comment]
Does mavlink-router stops it or is it ardupilot? And what failsafe?

**Comment by Dan-Moss** [comment]
> Does mavlink-router stop it or is it ardupilot? And what failsafe?

mavlink router stops it / splits up the log. the bin log on the FCU is complete armed/disarmed
any failsafe i have seen, so battery/rc/terrain

**Comment by Dan-Moss** [comment]
@lucasdemarchi the cause is that arducopter hits a failsafe, sets `MAV_STATE_CRITICAL`
mavlink router only looks for `MAV_STATE_ACTIVE` 

https://github.com/intel/mavlink-router/blob/2d095f315cf9a2a1c17c5d80657d2e42c6fb390c/src/mavlink-router/logendpoint.cpp#L439

https://github.com/ArduPilot/ardupilot/blob/04633d7e1c20a5ede7d1dafbd2e73f822acddaba/ArduCopter/GCS_Mavlink.cpp#L75

**Comment by lucasdemarchi** [comment]
Nice. Could you send a PR with that fix?

**Comment by Dan-Moss** [comment]
I see a couple of options:

using `MAV_STATE_ACTIVE` as a proxy for armed could also have critical and emergency added as to keep logging through a failsafe. however adding these would mean if a failsafe happened while disarmed this could create a log, so we could have a check to say only after it is active to then keep logging if critical and emergency. But in the case of a Battery low failsafe this could log until rebooting since the failsafe continues after landing. we could then look for flight termination as a way to stop the log?
![image](https://user-images.githubusercontent.com/50102283/97696243-35384580-1a9d-11eb-868b-758f1a30bbb5.png)

Another option is to use `MAV_MODE` and check all the armed modes?
![image](https://user-images.githubusercontent.com/50102283/97696148-0cb04b80-1a9d-11eb-81bc-08e309f5327e.png)

Do you have any thoughts?

Dan

**Comment by lucasdemarchi** [comment]
I think it's safe to change it to log on `state >= MAV_STATE_ACTIVE`. We rotate the log nonetheless if there is a timeout without receiving log data. 

If using mav_mode we should probably do:

```c++
bool armed = base_mode & MAV_MODE_FLAG_SAFETY_ARMED
```

Not sure why we didn't use it in the first place since it seems to be the correct check.

**Comment by lucasdemarchi** [comment]
@bkueng  this comes from your commit 1b48f691. AFAICS it would be ok for Ardupilot (test is needed). Would it work for PX4 as well?

**Comment by bkueng** [comment]
Yes, and using the base_mode would indeed be better, not sure why I didn't do the in the first place.
