### ISSUE TITLE
Unable to build on ARM64 Ubuntu 20.04

### ISSUE THREAD

**Issue by coderkalyan** [intel/mavlink-router#227]
I'm unable to build mavlink-router on an ARM64 VM running Ubuntu 20.04, the configure step fails with:
```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: linking file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:57: error: possibly undefined macro: AC_CHECK_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

I *think* all dependencies are installed, I installed what was listed in the README as well as ran `ldd mavlink-routerd`on a separate x86_64 VM that I was able to build succesfully on, and made sure all the libraries were available. However some quick googling reveals that this happens sometimes when dependencies are missing. Any idea what's up with this?

**Comment by hatakeyama-nst** [comment]
After installing pkg-config worked well for me.
